    version: '3.8'
    services:
      db:
        image: postgres:latest
        restart: no
        environment:
          POSTGRES_DB: my_postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - "5432:5432"
        volumes:
          - pgvol:/var/lib/postgresql/data

    volumes:
      pgvol:
